/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PoteriesRouteImport } from './routes/poteries'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as BonsaiIdRouteImport } from './routes/bonsai.$id'
import { Route as BonsaiNouveauRouteImport } from './routes/bonsai.nouveau'
import { Route as PoterieIdRouteImport } from './routes/poterie.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PoteriesRoute = PoteriesRouteImport.update({
  id: '/poteries',
  path: '/poteries',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const BonsaiIdRoute = BonsaiIdRouteImport.update({
  id: '/bonsai/$id',
  path: '/bonsai/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BonsaiNouveauRoute = BonsaiNouveauRouteImport.update({
  id: '/bonsai/nouveau',
  path: '/bonsai/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const PoterieIdRoute = PoterieIdRouteImport.update({
  id: '/poterie/$id',
  path: '/poterie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/collection': typeof CollectionRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/journal': typeof JournalRoute
  '/mcp': typeof McpRoute
  '/parametres': typeof ParametresRoute
  '/poteries': typeof PoteriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistiques': typeof StatistiquesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/bonsai/$id': typeof BonsaiIdRoute
  '/bonsai/nouveau': typeof BonsaiNouveauRoute
  '/poterie/$id': typeof PoterieIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/collection': typeof CollectionRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/journal': typeof JournalRoute
  '/mcp': typeof McpRoute
  '/parametres': typeof ParametresRoute
  '/poteries': typeof PoteriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistiques': typeof StatistiquesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/bonsai/$id': typeof BonsaiIdRoute
  '/bonsai/nouveau': typeof BonsaiNouveauRoute
  '/poterie/$id': typeof PoterieIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/collection': typeof CollectionRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/journal': typeof JournalRoute
  '/mcp': typeof McpRoute
  '/parametres': typeof ParametresRoute
  '/poteries': typeof PoteriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistiques': typeof StatistiquesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/bonsai/$id': typeof BonsaiIdRoute
  '/bonsai/nouveau': typeof BonsaiNouveauRoute
  '/poterie/$id': typeof PoterieIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendrier'
    | '/collection'
    | '/connexion'
    | '/inscription'
    | '/journal'
    | '/mcp'
    | '/parametres'
    | '/poteries'
    | '/sitemap.xml'
    | '/statistiques'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/bonsai/$id'
    | '/bonsai/nouveau'
    | '/poterie/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendrier'
    | '/collection'
    | '/connexion'
    | '/inscription'
    | '/journal'
    | '/mcp'
    | '/parametres'
    | '/poteries'
    | '/sitemap.xml'
    | '/statistiques'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/bonsai/$id'
    | '/bonsai/nouveau'
    | '/poterie/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/calendrier'
    | '/collection'
    | '/connexion'
    | '/inscription'
    | '/journal'
    | '/mcp'
    | '/parametres'
    | '/poteries'
    | '/sitemap.xml'
    | '/statistiques'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/bonsai/$id'
    | '/bonsai/nouveau'
    | '/poterie/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendrierRoute: typeof CalendrierRoute
  CollectionRoute: typeof CollectionRoute
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  JournalRoute: typeof JournalRoute
  McpRoute: typeof McpRoute
  ParametresRoute: typeof ParametresRoute
  PoteriesRoute: typeof PoteriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatistiquesRoute: typeof StatistiquesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BonsaiIdRoute: typeof BonsaiIdRoute
  BonsaiNouveauRoute: typeof BonsaiNouveauRoute
  PoterieIdRoute: typeof PoterieIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poteries': {
      id: '/poteries'
      path: '/poteries'
      fullPath: '/poteries'
      preLoaderRoute: typeof PoteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonsai/$id': {
      id: '/bonsai/$id'
      path: '/bonsai/$id'
      fullPath: '/bonsai/$id'
      preLoaderRoute: typeof BonsaiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonsai/nouveau': {
      id: '/bonsai/nouveau'
      path: '/bonsai/nouveau'
      fullPath: '/bonsai/nouveau'
      preLoaderRoute: typeof BonsaiNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poterie/$id': {
      id: '/poterie/$id'
      path: '/poterie/$id'
      fullPath: '/poterie/$id'
      preLoaderRoute: typeof PoterieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendrierRoute: CalendrierRoute,
  CollectionRoute: CollectionRoute,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  JournalRoute: JournalRoute,
  McpRoute: McpRoute,
  ParametresRoute: ParametresRoute,
  PoteriesRoute: PoteriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatistiquesRoute: StatistiquesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BonsaiIdRoute: BonsaiIdRoute,
  BonsaiNouveauRoute: BonsaiNouveauRoute,
  PoterieIdRoute: PoterieIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
