/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PoteriesRouteImport } from './routes/poteries'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoterieIdRouteImport } from './routes/poterie.$id'
import { Route as BonsaiNouveauRouteImport } from './routes/bonsai.nouveau'
import { Route as BonsaiIdRouteImport } from './routes/bonsai.$id'

const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PoteriesRoute = PoteriesRouteImport.update({
  id: '/poteries',
  path: '/poteries',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoterieIdRoute = PoterieIdRouteImport.update({
  id: '/poterie/$id',
  path: '/poterie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BonsaiNouveauRoute = BonsaiNouveauRouteImport.update({
  id: '/bonsai/nouveau',
  path: '/bonsai/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const BonsaiIdRoute = BonsaiIdRouteImport.update({
  id: '/bonsai/$id',
  path: '/bonsai/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/collection': typeof CollectionRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/journal': typeof JournalRoute
  '/parametres': typeof ParametresRoute
  '/poteries': typeof PoteriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistiques': typeof StatistiquesRoute
  '/bonsai/$id': typeof BonsaiIdRoute
  '/bonsai/nouveau': typeof BonsaiNouveauRoute
  '/poterie/$id': typeof PoterieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/collection': typeof CollectionRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/journal': typeof JournalRoute
  '/parametres': typeof ParametresRoute
  '/poteries': typeof PoteriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistiques': typeof StatistiquesRoute
  '/bonsai/$id': typeof BonsaiIdRoute
  '/bonsai/nouveau': typeof BonsaiNouveauRoute
  '/poterie/$id': typeof PoterieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/collection': typeof CollectionRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/journal': typeof JournalRoute
  '/parametres': typeof ParametresRoute
  '/poteries': typeof PoteriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistiques': typeof StatistiquesRoute
  '/bonsai/$id': typeof BonsaiIdRoute
  '/bonsai/nouveau': typeof BonsaiNouveauRoute
  '/poterie/$id': typeof PoterieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendrier'
    | '/collection'
    | '/connexion'
    | '/inscription'
    | '/journal'
    | '/parametres'
    | '/poteries'
    | '/sitemap.xml'
    | '/statistiques'
    | '/bonsai/$id'
    | '/bonsai/nouveau'
    | '/poterie/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendrier'
    | '/collection'
    | '/connexion'
    | '/inscription'
    | '/journal'
    | '/parametres'
    | '/poteries'
    | '/sitemap.xml'
    | '/statistiques'
    | '/bonsai/$id'
    | '/bonsai/nouveau'
    | '/poterie/$id'
  id:
    | '__root__'
    | '/'
    | '/calendrier'
    | '/collection'
    | '/connexion'
    | '/inscription'
    | '/journal'
    | '/parametres'
    | '/poteries'
    | '/sitemap.xml'
    | '/statistiques'
    | '/bonsai/$id'
    | '/bonsai/nouveau'
    | '/poterie/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendrierRoute: typeof CalendrierRoute
  CollectionRoute: typeof CollectionRoute
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  JournalRoute: typeof JournalRoute
  ParametresRoute: typeof ParametresRoute
  PoteriesRoute: typeof PoteriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatistiquesRoute: typeof StatistiquesRoute
  BonsaiIdRoute: typeof BonsaiIdRoute
  BonsaiNouveauRoute: typeof BonsaiNouveauRoute
  PoterieIdRoute: typeof PoterieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poteries': {
      id: '/poteries'
      path: '/poteries'
      fullPath: '/poteries'
      preLoaderRoute: typeof PoteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poterie/$id': {
      id: '/poterie/$id'
      path: '/poterie/$id'
      fullPath: '/poterie/$id'
      preLoaderRoute: typeof PoterieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonsai/nouveau': {
      id: '/bonsai/nouveau'
      path: '/bonsai/nouveau'
      fullPath: '/bonsai/nouveau'
      preLoaderRoute: typeof BonsaiNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonsai/$id': {
      id: '/bonsai/$id'
      path: '/bonsai/$id'
      fullPath: '/bonsai/$id'
      preLoaderRoute: typeof BonsaiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendrierRoute: CalendrierRoute,
  CollectionRoute: CollectionRoute,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  JournalRoute: JournalRoute,
  ParametresRoute: ParametresRoute,
  PoteriesRoute: PoteriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatistiquesRoute: StatistiquesRoute,
  BonsaiIdRoute: BonsaiIdRoute,
  BonsaiNouveauRoute: BonsaiNouveauRoute,
  PoterieIdRoute: PoterieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
